/**
 * Filesystem writes for project notes: atomic file replacement and the
 * AGENTS.md pointer-block maintenance. The exporter is the single writer of
 * the managed regions, so no locking is needed; atomic rename keeps readers
 * (and concurrent sessions rendering the same truth) from ever seeing a torn
 * file.
 *
 * Drift guard (P0-5): before overwriting a managed notes file the writer
 * re-reads the current on-disk content and compares it to the last content
 * this process wrote. When the file has been externally modified (hand edit,
 * merge conflict resolution, another tool), the write is refused and the
 * externally modified file is preserved as `<file>.bak.<ts>` so the user can
 * reconcile manually. The marker-based AGENTS.md pointer block is exempt:
 * it is already drift-safe (content outside the markers is never touched).
 *
 * @module @chenhw7/dsh-memory/notes/writer
 */

import { copyFile, mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'

/**
 * Write a file atomically: write to a sibling temp file, then rename.
 * Parent directories are created on demand.
 * @param filePath - the target file path.
 * @param content - the full file content.
 */
export async function writeFileAtomic(filePath: string, content: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true })
  const tmp = `${filePath}.${process.pid}.${Date.now()}.tmp`
  try {
    await writeFile(tmp, content, 'utf8')
    await rename(tmp, filePath)
  } catch (error) {
    await unlink(tmp).catch(() => {})
    throw error
  }
}

/** Thrown by {@link writeNotesFile} when the target file has drifted from the last write. */
export class DriftError extends Error {
  /** Absolute path of the backup copy holding the externally modified content. */
  readonly backupPath: string

  constructor(filePath: string, backupPath: string) {
    super(`notes file drifted: external modification detected at ${filePath}; backup saved to ${backupPath}`)
    this.name = 'DriftError'
    this.backupPath = backupPath
  }
}

/**
 * Write a managed notes file atomically with drift guard. Re-reads the
 * current on-disk content before writing; when the file differs from both
 * the previous content this process wrote (`previousContent`) AND the new
 * content (i.e. someone/something else modified the file), the write is
 * refused: the drifted file is copied to `<filePath>.bak.<ts>` and a
 * {@link DriftError} is thrown so the caller can decide what to do.
 *
 * The first write (file absent) is always allowed. A write that is a no-op
 * (new content equals what's on disk) is skipped silently.
 *
 * @param filePath - absolute path of the target file.
 * @param content - the full file content to write.
 * @param previousContent - the content this process last wrote to the file,
 *   or `undefined` when this is the first write in this process lifetime.
 * @throws {DriftError} when the on-disk content matches neither
 *   `previousContent` nor `content`.
 */
export async function writeNotesFile(
  filePath: string,
  content: string,
  previousContent: string | undefined,
): Promise<void> {
  let onDisk: string | undefined
  try {
    onDisk = await readFile(filePath, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  if (onDisk !== undefined) {
    // No-op: content already on disk matches what we want to write.
    if (onDisk === content) return
    // Drift: the on-disk content does not match our last write — someone
    // else (hand edit, merge tool, another process) modified the file.
    const drifted = previousContent === undefined || onDisk !== previousContent
    if (drifted) {
      const backupPath = `${filePath}.bak.${Date.now()}`
      await copyFile(filePath, backupPath)
      throw new DriftError(filePath, backupPath)
    }
  }
  await writeFileAtomic(filePath, content)
}

/** Marker opening the managed pointer block in AGENTS.md. */
export const AGENTS_POINTER_BEGIN = '<!-- dsh-memory:begin -->'
/** Marker closing the managed pointer block in AGENTS.md. */
export const AGENTS_POINTER_END = '<!-- dsh-memory:end -->'

/** The managed pointer block text for a given notes directory (repo-relative). */
export function agentsPointerBlock(notesDir: string): string {
  return `${AGENTS_POINTER_BEGIN}\n> Agent-maintained project notes live in \`${notesDir}/\` (auto-generated by dsh-memory — do not edit those files by hand).\n${AGENTS_POINTER_END}`
}

/**
 * Ensure the AGENTS.md pointer block exists. Creates a pointer-only AGENTS.md
 * when absent; replaces an existing managed block in place (idempotent:
 * rewrites only when the block text actually changed); appends the block when
 * the file exists without one. Everything outside the markers is untouched.
 * @param agentsPath - absolute path of the repository's AGENTS.md.
 * @param notesDir - repo-relative notes directory named in the pointer.
 */
export async function ensureAgentsPointer(agentsPath: string, notesDir: string): Promise<void> {
  const block = agentsPointerBlock(notesDir)
  let existing: string | undefined
  try {
    existing = await readFile(agentsPath, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  if (existing === undefined) {
    await writeFileAtomic(agentsPath, `${block}\n`)
    return
  }
  const beginIdx = existing.indexOf(AGENTS_POINTER_BEGIN)
  const endIdx = existing.indexOf(AGENTS_POINTER_END)
  if (beginIdx >= 0 && endIdx > beginIdx) {
    const next = existing.slice(0, beginIdx) + block + existing.slice(endIdx + AGENTS_POINTER_END.length)
    if (next !== existing) await writeFileAtomic(agentsPath, next)
    return
  }
  const separator = existing.endsWith('\n') ? '\n' : '\n\n'
  await writeFileAtomic(agentsPath, existing + separator + block + '\n')
}
