/**
 * Filesystem writes for project notes: atomic file replacement and the
 * AGENTS.md pointer-block maintenance. The exporter is the single writer of
 * the managed regions, so no locking is needed; atomic rename keeps readers
 * (and concurrent sessions rendering the same truth) from ever seeing a torn
 * file.
 *
 * @module @chenhw7/dsh-memory/notes/writer
 */

import { mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'

/**
 * Write a file atomically: write to a sibling temp file, then rename.
 * Parent directories are created on demand.
 * @param filePath - the target file path.
 * @param content - the full file content.
 */
export async function writeFileAtomic(filePath: string, content: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true })
  const tmp = `${filePath}.${process.pid}.${Date.now()}.tmp`
  try {
    await writeFile(tmp, content, 'utf8')
    await rename(tmp, filePath)
  } catch (error) {
    await unlink(tmp).catch(() => {})
    throw error
  }
}

/** Marker opening the managed pointer block in AGENTS.md. */
export const AGENTS_POINTER_BEGIN = '<!-- dsh-memory:begin -->'
/** Marker closing the managed pointer block in AGENTS.md. */
export const AGENTS_POINTER_END = '<!-- dsh-memory:end -->'

/** The managed pointer block text for a given notes directory (repo-relative). */
export function agentsPointerBlock(notesDir: string): string {
  return `${AGENTS_POINTER_BEGIN}\n> Agent-maintained project notes live in \`${notesDir}/\` (auto-generated by dsh-memory — do not edit those files by hand).\n${AGENTS_POINTER_END}`
}

/**
 * Ensure the AGENTS.md pointer block exists. Creates a pointer-only AGENTS.md
 * when absent; replaces an existing managed block in place (idempotent:
 * rewrites only when the block text actually changed); appends the block when
 * the file exists without one. Everything outside the markers is untouched.
 * @param agentsPath - absolute path of the repository's AGENTS.md.
 * @param notesDir - repo-relative notes directory named in the pointer.
 */
export async function ensureAgentsPointer(agentsPath: string, notesDir: string): Promise<void> {
  const block = agentsPointerBlock(notesDir)
  let existing: string | undefined
  try {
    existing = await readFile(agentsPath, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  if (existing === undefined) {
    await writeFileAtomic(agentsPath, `${block}\n`)
    return
  }
  const beginIdx = existing.indexOf(AGENTS_POINTER_BEGIN)
  const endIdx = existing.indexOf(AGENTS_POINTER_END)
  if (beginIdx >= 0 && endIdx > beginIdx) {
    const next = existing.slice(0, beginIdx) + block + existing.slice(endIdx + AGENTS_POINTER_END.length)
    if (next !== existing) await writeFileAtomic(agentsPath, next)
    return
  }
  const separator = existing.endsWith('\n') ? '\n' : '\n\n'
  await writeFileAtomic(agentsPath, existing + separator + block + '\n')
}
